# Generated by Django 5.0.3 on 2024-03-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.CharField(default='', editable=False, max_length=50, verbose_name='Дата производства'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_images/', verbose_name='Изображение'),
        ),
    ]
