# Generated by Django 5.0.3 on 2024-04-06 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_manufactured_at_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_creation',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_last_change',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufactured_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория'),
        ),
    ]
